# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EasyApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for EasyApp
inhibit_all_warnings!

pod 'SDWebImage'
pod 'DateTools'
pod 'YYText'
pod 'Masonry'

  target 'EasyAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EasyAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
